<?php require_once 'layout/header.phtml'; ?>

<form action="home" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Editar nombre</label>
                <input name="nombre" type="text" class="form-control">
            </div>
        </div>

    <div class="form-group">
        <label>Editar imagen (URL)</label>
        <input name="imagen" class="form-control" rows="3">
    </div>

    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>

<?php require_once 'layout/footer.phtml'; ?>