<?php require_once 'layout/header.phtml';?>

<form action="updateMarca/<?= $id_marca ?>" method="POST" enctype="multipart/form-data" class="my-4">
        <div class="row m-4">
            <div class="col-12">
                <div class="form-group">
                    <label>Agregar marca</label>
                    <input name="nombre" type="text" class="form-control">
                </div>
            </div>
        </div>
        <div class="row m-4">
            <div class="col-12">
                <div class="form-group">
                    <label>Imagen (URL)</label>
                    <label>Imagen (URL)</label>
                    <input name="imagen" type="file" class="form-control" id="imagen" accept="image/*">
                </div>
            </div>
        </div>

        <div class="row m-4">
            <div class="col-4">
                <button type="submit" class="btn btn-primary mt-4">Guardar</button>
            </div>
        </div>
    </form>

<?php require_once 'layout/footer.phtml'; ?>