<div class="container mx-auto">
    <h1>Agregar marca</h1>

    <form action="addMarca" method="POST" class="my-4">
        <div class="row m-4">
            <div class="col-12">
                <div class="form-group">
                    <label>Agregar marca</label>
                    <input name="nombre" type="text" class="form-control">
                </div>
            </div>
        </div>
        <div class="row m-4">
            <div class="col-12">
                <div class="form-group">
                    <label>Imagen (URL)</label>
                    <input name="imagen" class="form-control" rows="3">
                </div>
            </div>
        </div>

        <div class="row m-4">
            <div class="col-4">
                <button type="submit" class="btn btn-primary mt-4">Guardar</button>
            </div>
        </div>
    </form>
</div>