<form action="addMarca" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Agregar marca</label>
                <input name="nombre" type="text" class="form-control">
            </div>
        </div>

    <div class="form-group">
        <label>Imagen (URL)</label>
        <input name="imagen" class="form-control" rows="3">
    </div>

    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>