<?php require_once 'layout/header.phtml'; ?>

<?php if ($this->user)
    require_once 'marcas.form.phtml'; ?>

<section class="container-lg mx-auto px-4">
    <h1>Marcas Disponibles</h1>
    <div class=" d-flex flex-row flex-wrap justify-content-center">
        <?php foreach ($marcas as $marca): ?>
            <div class="card m-3 col-12 col-md-4 col-lg-3 shadow">
                <?php if ($marca->imagen): ?>
                    <img src="<?= BASE_URL . $marca->imagen ?>" class="card-img-top" alt="Imagen de <?= $marca->modelo ?>">
                <?php endif; ?>
                <div class="card-body d-flex flex-column">
                    <a href="showVehiculosPorMarca/<?= $marca->id_marca ?>" class="card-title fw-bold text-decoration-none">
                        <?= $marca->nombre ?>
                    </a>
                    <div class="d-flex justify-content-between align-items-end">
                        <?php if ($this->user): ?>
                            <a href="confirmacionDeleteMarca/<?= $marca->id_marca ?>" class="btn btn-danger">Borrar</a>
                            <a href="updateFormMarca/<?= $marca->id_marca ?>" class="btn btn-success">Editar</a>

                        <?php endif; ?>
                        <a href="showVehiculosPorMarca/<?= $marca->id_marca ?>" class="btn btn-primary">Ver</a>
                    </div>
                </div>
            </div>
        <?php endforeach ?>
    </div>
</section>

<?php require_once 'layout/footer.phtml'; ?>