<?php require_once 'layout/header.phtml'; ?>


<?php if ($this->user) 
    require_once 'marcas.form.phtml'; ?>

<div class="container mx-auto">
    <h1>Marcas Disponibles</h1>
    <div class=" d-flex flex-row flex-wrap justify-content-center">
        <?php foreach ($marcas as $marca): ?>
            <div class="card m-3 w-25 shadow">
                <?php if ($marca->imagen): ?>
                    <img src="<?= BASE_URL . $marca->imagen ?>" class="card-img-top"
                        alt="Imagen de <?= $marca->modelo ?>">
                <?php endif; ?>
                <div class="card-body d-flex flex-column">
                    <div class="card-title my-4">
                        <a href="showVehiculosPorMarca/<?= $marca->id_marca ?>"
                            class="card-title fw-bold text-decoration-none">
                            <?= $marca->nombre ?>
                        </a>
                    </div>
                    <div class="d-flex justify-content-between mt-auto">
                        <?php if ($this->user) : ?>
                        <a href="deleteMarca/<?= $marca->id_marca ?>" class="btn btn-danger">Borrar</a>
                        <a href="updateFormMarca/<?= $marca->id_marca ?>" class="btn btn-success">Editar</a>

                        <?php endif; ?>
                        <a href="showVehiculosPorMarca/<?= $marca->id_marca ?>" class="btn btn-primary">Ver marca</a>

                    </div>
                </div>
            </div>
        <?php endforeach ?>
    </div>
</div>

<?php require_once 'layout/footer.phtml'; ?>