<?php require_once 'layout/header.phtml' ?>

<?php if($error):?>
    <h4><?=$error?></h4>
<?php endif ?>

<div class="container mx-auto">
    <h1>Registrarse</h1>

    <form action="singUp" method="POST" class="my-4">
        <div class="row m-4">
            <div class="col-12">
                <div class="form-group">
                    <label>Nombre</label>
                    <input name="nombre" type="text" class="form-control">
                </div>
            </div>
        </div>
        <div class="row m-4">
            <div class="col-12">
                <div class="form-group">
                    <label>Nombre de usuario</label>
                    <input name="nombre_usuario" type="text" class="form-control">
                </div>
            </div>
        </div>
        <div class="row m-4">
            <div class="col-12">
                <div class="form-group">
                    <label>Contraseña</label>
                    <input name="contraseña" type="password" class="form-control" rows="3">
                </div>
            </div>
        </div>

        <div class="row m-4">
            <div class="col-4">
                <button type="submit" class="btn btn-primary mt-4">Registrarse</button>
            </div>
        </div>
    </form>
</div>

<?php require_once 'layout/footer.phtml' ?>
