<?php require_once 'layout/header.phtml'; ?>

<?php if ($this->user)
    require_once 'vehiculos.form.phtml'; ?>

<section class="container mx-auto">
    <h1>Listado de Vehículos Disponibles</h1>
    <div class=" d-flex flex-row flex-wrap justify-content-center ">
        <?php foreach ($vehiculos as $vehiculo): ?>
            <div class="card m-3 col-12 col-md-4 col-lg-3 shadow ">
                <?php if ($vehiculo->imagen): ?>
                    <img src="<?= BASE_URL . $vehiculo->imagen ?>" class="card-img-top"
                        alt="Imagen de <?= $vehiculo->modelo ?>">
                <?php endif; ?>
                <div class="card-body d-flex flex-column ">
                    <a href="showVehiculo/<?= $vehiculo->id_vehiculo ?>" class="card-title fw-bold text-decoration-none">
                        <h2 class="card-title"> <?= $vehiculo->modelo ?> </h2>
                    </a>
                    <a href="showVehiculosPorMarca/<?= $vehiculo->marca ?>" class="card-subtitle text-decoration-none mb-2">
                        <h5 class="card-subtitle"><?= $vehiculo->nombreMarca ?></h5>
                    </a>

                    <div class="d-flex justify-content-between align-items-end">
                        <?php if ($this->user): ?>
                            <a href="deleteVehiculo/<?= $vehiculo->id_vehiculo ?>" class="btn btn-danger">Borrar</a>
                            <a href="updateFormVehiculo/<?= $vehiculo->id_vehiculo ?>" class="btn btn-success">Editar</a>
                        <?php endif; ?>
                        <a href="showVehiculo/<?= $vehiculo->id_vehiculo ?>" class="btn btn-primary">Ver</a>
                    </div>
                </div>
            </div>
        <?php endforeach ?>
    </div>
</section>

<?php require_once 'layout/footer.phtml'; ?>