<?php require_once 'layout/header.phtml'; ?>

<?php require_once 'vehiculos.form.phtml'; ?>
<section class="container mx-auto">
    <h1>Listado de Vehículos Disponibles</h1>
    <div class=" d-flex flex-row flex-wrap justify-content-center ">

        <?php
        if ($marca) :
            foreach ($vehiculos as $vehiculo): ?>
                <div class="card m-3 col-12 col-md-4 col-lg-3 shadow">
                    <?php if ($vehiculo->imagen): ?>
                        <img src="<?= BASE_URL . $vehiculo->imagen ?>" class="card-img-top" alt="Imagen de 
                <?= $vehiculo->modelo ?>">
                    <?php endif; ?>
                    <div class="card-body d-flex flex-column ">
                        <a href="showVehiculo/<?= $vehiculo->id_vehiculo ?>" class="card-title fw-bold text-decoration-none">
                            <h2 class="card-title"> <?= $vehiculo->modelo ?> </h2>
                        </a>
                        
                    
                        <a href="showVehiculosPorMarca/<?= $vehiculo->marca ?>" class="card-subtitle text-decoration-none mb-2">
                            <h5 class="card-subtitle"><?= $marca->nombre ?></h5>
                        </a>

                        <div class="d-flex justify-content-between align-items-end">
                            <a href="deleteVehiculo/<?= $vehiculo->id_vehiculo ?>" class="btn btn-danger">Borrar</a>
                            <a href="updateFormVehiculo/<?= $vehiculo->id_vehiculo ?>" class="btn btn-success">Editar</a>
                            <a href="showVehiculo/<?= $vehiculo->id_vehiculo ?>" class="btn btn-primary">Ver</a>
                        </div>
                    </div>
                </div>
            <?php endforeach ?>
            
            <?php elseif($marcas) :
                foreach ($vehiculos as $vehiculo): ?>
                <div class="card-body d-flex flex-column ">
                        <a href="showVehiculo/<?= $vehiculo->id_vehiculo ?>" class="card-title fw-bold text-decoration-none">
                            <h2 class="card-title"> <?= $vehiculo->modelo ?> </h2>
                        </a>
                        
                    
                        <a href="showVehiculosPorMarca/<?= $vehiculo->marca ?>" class="card-subtitle text-decoration-none mb-2">
                            
                            <h5 class="card-subtitle"><?php 
                                foreach ($marcas as $marca) {
                                    if ($vehiculo->marca == $marca->id_marca) {
                                        $nombreMarca = $marca->nombre;
                                }
                            }

                                  ?><?= $nombreMarca ?>
                                   </h5>
                        </a>

                        <div class="d-flex justify-content-between align-items-end">
                            <a href="deleteVehiculo/<?= $vehiculo->id_vehiculo ?>" class="btn btn-danger">Borrar</a>
                            <a href="updateFormVehiculo/<?= $vehiculo->id_vehiculo ?>" class="btn btn-success">Editar</a>
                            <a href="showVehiculo/<?= $vehiculo->id_vehiculo ?>" class="btn btn-primary">Ver</a>
                        </div>
                    </div>
                </div>
            <?php endforeach ?>

        <?php endif; ?>
    </div>

    <?php require_once 'layout/footer.phtml'; ?>
</section>

<?php require_once 'layout/footer.phtml'; ?>