<?php require_once 'layout/header.phtml'; ?>

<?php require_once 'vehiculos.form.phtml'; ?>

<div class="container mx-auto d-flex flex-row flex-wrap justify-content-center ">
    <?php foreach ($vehiculos as $vehiculo): ?>
        <div class="card m-3 col-12 col-md-4 col-lg-3 shadow ">
            <?php if ($vehiculo->imagen): ?>
                <img src="<?= BASE_URL . $vehiculo->imagen ?>" class="card-img-top" alt="Imagen de 
                <?= $vehiculo->modelo ?>">
            <?php endif; ?>
            <div class="card-body d-flex flex-column ">
                <h2 class="card-title"> <?= $vehiculo->modelo ?> </h2>
                <?php
                $nombreMarca = "Marca desconocida";
                foreach ($marcas as $marca) {
                    if ($marca->id_marca == $vehiculo->marca) {
                        $nombreMarca = $marca->nombre;
                        break;
                    }
                }
                ?>
                <a href="<?= BASE_URL ?>showVehiculosPorMarca/<?= $vehiculo->marca ?>" class="card-subtitle text-decoration-none mb-2"><h5 class="card-subtitle"><?= $nombreMarca ?></h5></a>
                
                <div class="d-flex justify-content-between align-items-end">
                    <a href="deleteVehiculo/<?= $vehiculo->id_vehiculo ?>" class="btn btn-danger">Borrar</a>
                    <a href="<?= BASE_URL ?>updateFormVehiculo/<?= $vehiculo->id_vehiculo ?>" class="btn btn-success">Editar</a>
                    <a href="<?= BASE_URL ?>showVehiculo/<?= $vehiculo->id_vehiculo ?>" class="btn btn-primary">Ver</a>
                </div>
            </div>
        </div>
    <?php endforeach ?>
</div>

<?php require_once 'layout/footer.phtml'; ?>