<div class="container mx-auto">
    <h1>Agregar Vehiculo</h1>
    <form action="addVehiculo" method="POST" enctype="multipart/form-data" class="my-4 ">
        <div class="row m-4">
            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label>Marca</label>
                    <select name="marca" class="form-control">
                        <?php foreach ($marcas as $marca): ?>
                            <option value="<?= $marca->id_marca ?>"><?= $marca->nombre ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </div>
            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label>Modelo</label>
                    <input name="modelo" type="text" class="form-control">
                </div>
            </div>
        </div>

        <div class="row m-4">
            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label>Descripción</label>
                    <textarea name="descripcion" class="form-control"></textarea>
                </div>
            </div>
            <div class="col-12 col-md-6">
                <div class="form-group">
                    <label>Imagen (URL)</label>
                    <input name="imagen" type="file" class="form-control" id="imagen" accept="image/*">
                </div>
            </div>
        </div>

        <div class="row m-4">
            <div class="col-12 col-md-6">
                <button type="submit" class="btn btn-primary mt-4">Guardar</button>
            </div>
        </div>


    </form>
</div>