<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="<?php echo BASE_URL ?>" />
    <link rel="stylesheet" href="css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title> Concesionaria </title>
</head>
<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid d-flex flex-column flex-md-row align-items-center">
    <a class="navbar-brand pl-4 hidden md-block text-center md:text-left" href="home">Concesionaria M & M</a>
    <div class="navbar-collapse d-flex flex-md-row " id="navbarNavAltMarkup">
      <div class=" mx-auto text-center d-md-flex gap-4 flex-md-row">
        <a class="nav-link active" aria-current="page" href="home">Home</a>
        <a class="nav-link" href="showVehiculos">Vehiculos</a>
        
        <a class="nav-link" href="logout">
          <?php if ($this->user) : ?>
            Cerrar sesion
          <?php else : ?>
            Iniciar sesion
          <?php endif; ?>
        </a>
      </div>
    </div>
  </div>
</nav>